
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dzaky
 */
public class Riwayat extends javax.swing.JFrame {
    
    

    /**
     * Creates new form Riwayat
     */
    public String nmcustomer;
    public TIKETANBIOSKOP tiketanbioskop;
    //public login login;
    public Riwayat(String nmcustomer2) {
        initComponents();
        this.nmcustomer = nmcustomer2;
        //JOptionPane.showMessageDialog(null, this.nmcustomer);
    }
    
    public Riwayat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        txt1 = new javax.swing.JTextArea();
        btn_kembali = new javax.swing.JButton();
        btn_next = new javax.swing.JButton();
        btn_del = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Riwayat");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt1.setColumns(20);
        txt1.setRows(5);
        jScrollPane2.setViewportView(txt1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 310, 210));

        btn_kembali.setBackground(new java.awt.Color(207, 212, 216));
        btn_kembali.setText("Kembali");
        btn_kembali.setBorder(null);
        btn_kembali.setContentAreaFilled(false);
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btn_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 90, 30));

        btn_next.setBackground(new java.awt.Color(207, 212, 216));
        btn_next.setText("PRINT");
        btn_next.setBorder(null);
        btn_next.setContentAreaFilled(false);
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });
        getContentPane().add(btn_next, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 90, 30));

        btn_del.setBackground(new java.awt.Color(207, 212, 216));
        btn_del.setText("DELETE ALL");
        btn_del.setBorder(null);
        btn_del.setBorderPainted(false);
        btn_del.setContentAreaFilled(false);
        btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delActionPerformed(evt);
            }
        });
        getContentPane().add(btn_del, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 90, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("A:\\riwaya.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed

     try {
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    
    
    // Mengatur koneksi
    koneksi DB = new koneksi();
    DB.config();
    con = DB.con;
    stat = DB.stm;
    
    // Query untuk mengambil riwayat
    //JOptionPane.showMessageDialog(null, this.nmcustomer);
    sql = "SELECT * FROM riwayat where nama = '"+ this.nmcustomer +"'";
    //JOptionPane.showMessageDialog(null, sql);
    //sql = "SELECT * FROM riwayat ";
    rs = stat.executeQuery(sql);
    
    // Proses hasil query untuk format ke dalam JTextArea
    StringBuilder sb = new StringBuilder();
    while(rs.next()) {
        String nama = rs.getString("nama");
        String total = rs.getString("Total");
        String pembayaran = rs.getString("Pembayaran");
        String harga = rs.getString("Harga");
        String film = rs.getString("Film");
        
        // Format data sesuai yang diinginkan, misalnya:
        sb.append("Nama Pembeli: ").append(nama).append("\n");
        sb.append("Total Pembayaran: ").append(total).append("\n");
        sb.append("Pembayaran: ").append(pembayaran).append("\n");
        sb.append("Harga: ").append(harga).append("\n");
        sb.append("Film: ").append(film).append("\n");
        sb.append("------------------------\n");
    }
    
    // Set teks yang sudah diformat ke dalam JTextArea
    //JOptionPane.showMessageDialog(null, sb);
    txt1.setText(sb.toString());
    
    
    // Menutup koneksi dan resource
    rs.close();
    stat.close();
    con.close();
} catch (Exception e) {
    e.printStackTrace();
}   





           
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delActionPerformed
        // TODO add your handling code here:
        Connection con;
        Statement stat;
        String sql;

        // Membuat koneksi ke database
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;

        try {
            // SQL Query untuk menghapus semua data dari tabel
            String deleteQuery = "DELETE FROM riwayat";

            // Eksekusi query
            int rowsAffected = stat.executeUpdate(deleteQuery);

            // Tampilkan pesan konfirmasi di JTextArea
            if (rowsAffected > 0) {
                txt1.setText("Semua data dalam tabel 'riwayat' telah dihapus.");
            } else {
                txt1.setText("Tabel 'riwayat' sudah kosong.");
            }
        } catch (Exception e) {
            e.printStackTrace();
            txt1.setText("Terjadi kesalahan saat menghapus data: " + e.getMessage());
        }
    
    }//GEN-LAST:event_btn_delActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Riwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Riwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Riwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Riwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Riwayat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_del;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_next;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txt1;
    // End of variables declaration//GEN-END:variables
}
