
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.management.StringValueExp;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dzaky
 */
public class TIKETANBIOSKOP extends javax.swing.JFrame {
    int reguler,ultra,gold,harga,beli,total,bayar,kembali;
    String namauser;
    
    
    
    
    
    /**
     * Creates new form TIKETANBIOSKOP
     */
    public TIKETANBIOSKOP(String namauser) {
        initComponents();
        this.namauser = namauser;
        txt_nama.setText(namauser);
    }
    
    public void updateHarga() {
    if (Kursi.getSelectedItem().equals("Pilih Kursi")) {
        buttonGroup1.clearSelection();
        txt_harga.setText("");
    } 
    else if (Kursi.getSelectedItem().equals("A")) { 
        reguler = 50000;
        ultra = 75000;
        gold = 90000;
    }
    else if (Kursi.getSelectedItem().equals("B")) { 
        reguler = 45000;
        ultra = 70000;
        gold = 85000;
    }
    else if (Kursi.getSelectedItem().equals("C")) { 
        reguler = 40000;
        ultra = 65000;
        gold = 80000;
    }
    else if (Kursi.getSelectedItem().equals("D")) { 
        reguler = 40000;
        ultra = 60000;
        gold = 80000;
    }
}
    
    public class Transaction {
    private String jumlahBeli;
    private int harga;
    private int pembayaran;
    private int totalBayar;
    private int kembalian;

    public Transaction(String jumlahBeli, int harga, int pembayaran, int totalBayar) {
        this.jumlahBeli = jumlahBeli;
        this.harga = harga;
        this.pembayaran = pembayaran;
        this.totalBayar = totalBayar;
    }

    public boolean isJumlahBeliValid() {
        jumlahBeli = jumlahBeli.trim();
        return !(jumlahBeli.isBlank() || jumlahBeli.isEmpty());
    }

    public void calculateTotalBayar() {
        int jumlah = Integer.parseInt(jumlahBeli);
        totalBayar = harga * jumlah;
    }

    public boolean isPembayaranSufficient() {
        return pembayaran >= totalBayar;
    }

    public int calculateKembalian() {
        kembalian = pembayaran - totalBayar;
        return kembalian;
    }

    public void showMessage(String message, String title) {
        JOptionPane.showMessageDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
    }

    // Getters
    public int getTotalBayar() {
        return totalBayar;
    }

    public int getKembalian() {
        return kembalian;
    }
}
    
    
    
    public void handleKursiSelection() {
        if (!rb_film1.isSelected() && !rb_film2.isSelected() && !rb_film3.isSelected()) {
            showMessage("Silakan pilih film terlebih dahulu.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            Kursi.setSelectedIndex(0);
            return;
        }
        updateHarga();
    }
    
     public void resetInput() {
        buttonGroup1.clearSelection();
        txt_harga.setText("");
        Kursi.setSelectedItem("pilih jenis tiket");
        txt_totalbayar.setText("");
        txt_jumlahbeli.setText("");
        txt_pembayaran.setText("");
        txt_kembalian.setText("");
        txt_film.setText("");
        txt_area.setText("");
        buttonGroup2.clearSelection();
        Kursi.setSelectedIndex(0);
    }

     
    private void showMessage(String message, String title, int messageType) {
        JOptionPane.showMessageDialog(null, message, title, messageType);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Kursi = new javax.swing.JComboBox<>();
        rb_reguler = new javax.swing.JRadioButton();
        rb_ultraxd = new javax.swing.JRadioButton();
        rb_gold = new javax.swing.JRadioButton();
        txt_harga = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        txt_jumlahbeli = new javax.swing.JTextField();
        txt_totalbayar = new javax.swing.JTextField();
        txt_pembayaran = new javax.swing.JTextField();
        txt_kembalian = new javax.swing.JTextField();
        Namafil = new javax.swing.JLabel();
        txt_film = new javax.swing.JTextField();
        btn_input = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        btn_print = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area = new javax.swing.JTextArea();
        rb_film1 = new javax.swing.JRadioButton();
        rb_film2 = new javax.swing.JRadioButton();
        rb_film3 = new javax.swing.JRadioButton();
        txt_riwayat = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Movies");

        jPanel1.setBackground(new java.awt.Color(255, 255, 232));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Kursi.setBackground(new java.awt.Color(207, 212, 216));
        Kursi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "A", "B", "C", "D" }));
        Kursi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KursiActionPerformed(evt);
            }
        });
        jPanel1.add(Kursi, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 265, -1, -1));

        buttonGroup1.add(rb_reguler);
        rb_reguler.setText("Reguler");
        rb_reguler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_regulerActionPerformed(evt);
            }
        });
        jPanel1.add(rb_reguler, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        buttonGroup1.add(rb_ultraxd);
        rb_ultraxd.setText("ultra xd");
        rb_ultraxd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_ultraxdActionPerformed(evt);
            }
        });
        jPanel1.add(rb_ultraxd, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, -1));

        buttonGroup1.add(rb_gold);
        rb_gold.setText("Gold");
        rb_gold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_goldActionPerformed(evt);
            }
        });
        jPanel1.add(rb_gold, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 365, -1, -1));

        txt_harga.setEditable(false);
        txt_harga.setBackground(new java.awt.Color(207, 212, 216));
        txt_harga.setBorder(null);
        txt_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hargaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 412, 150, 30));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Data Pembelian"));

        jLabel5.setText("Nama");

        jLabel6.setText("Jumlah beli");

        jLabel7.setText("Total bayar");

        jLabel8.setText("Pembayaran");

        jLabel9.setText("Kembalian");

        txt_nama.setEditable(false);
        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });

        txt_jumlahbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jumlahbeliActionPerformed(evt);
            }
        });
        txt_jumlahbeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_jumlahbeliKeyReleased(evt);
            }
        });

        txt_totalbayar.setEditable(false);
        txt_totalbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalbayarActionPerformed(evt);
            }
        });

        txt_pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pembayaranActionPerformed(evt);
            }
        });
        txt_pembayaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_pembayaranKeyReleased(evt);
            }
        });

        txt_kembalian.setEditable(false);
        txt_kembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kembalianActionPerformed(evt);
            }
        });

        Namafil.setText("Film");

        txt_film.setEditable(false);
        txt_film.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_filmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Namafil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_film, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_jumlahbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_totalbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_jumlahbeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_totalbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Namafil)
                    .addComponent(txt_film, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 455, 280, 200));

        btn_input.setBackground(new java.awt.Color(207, 212, 216));
        btn_input.setText("clear");
        btn_input.setBorder(null);
        btn_input.setContentAreaFilled(false);
        btn_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inputActionPerformed(evt);
            }
        });
        jPanel1.add(btn_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 90, 40));

        btn_keluar.setBackground(new java.awt.Color(207, 212, 216));
        btn_keluar.setText("Keluar");
        btn_keluar.setBorder(null);
        btn_keluar.setContentAreaFilled(false);
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 655, 70, 35));

        btn_print.setBackground(new java.awt.Color(207, 212, 216));
        btn_print.setText("Print data");
        btn_print.setBorder(null);
        btn_print.setBorderPainted(false);
        btn_print.setContentAreaFilled(false);
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });
        jPanel1.add(btn_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 80, 40));

        txt_area.setEditable(false);
        txt_area.setColumns(20);
        txt_area.setRows(5);
        txt_area.setBorder(null);
        txt_area.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(txt_area);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 290, 190));

        buttonGroup2.add(rb_film1);
        rb_film1.setText("Her");
        rb_film1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_film1ActionPerformed(evt);
            }
        });
        jPanel1.add(rb_film1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        buttonGroup2.add(rb_film2);
        rb_film2.setText("Bladerunner");
        rb_film2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_film2ActionPerformed(evt);
            }
        });
        jPanel1.add(rb_film2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, -1, -1));

        buttonGroup2.add(rb_film3);
        rb_film3.setText("Drive");
        rb_film3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_film3ActionPerformed(evt);
            }
        });
        jPanel1.add(rb_film3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, -1, -1));

        txt_riwayat.setBackground(new java.awt.Color(207, 212, 216));
        txt_riwayat.setText("Riwayat");
        txt_riwayat.setBorder(null);
        txt_riwayat.setContentAreaFilled(false);
        txt_riwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_riwayatActionPerformed(evt);
            }
        });
        jPanel1.add(txt_riwayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 80, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon("A:\\Kursi.png")); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 740, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rb_regulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_regulerActionPerformed
        // TODO add your handling code here:
        if (Kursi.getSelectedIndex() == 0) {
    JOptionPane.showMessageDialog(this, "Please select a kursi from the combo box.", "Error", JOptionPane.ERROR_MESSAGE);
    buttonGroup1.clearSelection();
    } else if (rb_reguler.isSelected()) {
    txt_harga.setText(String.valueOf(reguler));
    }

    }//GEN-LAST:event_rb_regulerActionPerformed

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void txt_jumlahbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jumlahbeliActionPerformed
        // TODO add your handling code here:

        
        beli = Integer.parseInt(txt_jumlahbeli.getText());
        harga = Integer.parseInt(txt_harga.getText());
        total = beli * harga;
        txt_totalbayar.setText(String.valueOf(total));

    }//GEN-LAST:event_txt_jumlahbeliActionPerformed

    private void txt_totalbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalbayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalbayarActionPerformed

    private void txt_pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pembayaranActionPerformed
    String jumlahBeli = txt_jumlahbeli.getText();
    int harga = Integer.parseInt(txt_harga.getText());
    int pembayaran = Integer.parseInt(txt_pembayaran.getText());
    int totalBayar;

    if (txt_totalbayar.getText().isEmpty()) {
        totalBayar = 0;
    } else {
        totalBayar = Integer.parseInt(txt_totalbayar.getText());
    }

    Transaction transaction = new Transaction(jumlahBeli, harga, pembayaran, totalBayar);

    if (!transaction.isJumlahBeliValid()) {
        transaction.showMessage("Jumlah beli masih kosong", "ERROR");
        txt_jumlahbeli.setText("");
        txt_pembayaran.setText("");
    } else {
        transaction.calculateTotalBayar();
        txt_totalbayar.setText(String.valueOf(transaction.getTotalBayar()));

        if (!transaction.isPembayaranSufficient()) {
            transaction.showMessage("Pembayaran Kurang", "ERROR");
        } else {
            int kembalian = transaction.calculateKembalian();
            txt_kembalian.setText(String.valueOf(kembalian));
        }
    }
       
       
        
        

    }//GEN-LAST:event_txt_pembayaranActionPerformed

    private void txt_kembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kembalianActionPerformed

    private void KursiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KursiActionPerformed
        // TODO add your handling code here:
        handleKursiSelection();
    }//GEN-LAST:event_KursiActionPerformed

    private void rb_ultraxdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_ultraxdActionPerformed
if (Kursi.getSelectedIndex() == 0) {
    JOptionPane.showMessageDialog(this, "Please select a kursi from the combo box.", "Error", JOptionPane.ERROR_MESSAGE);
    buttonGroup1.clearSelection();
    } else if (rb_ultraxd.isSelected()) {
    txt_harga.setText(String.valueOf(ultra));
    }
    }//GEN-LAST:event_rb_ultraxdActionPerformed

    private void rb_goldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_goldActionPerformed
       if (Kursi.getSelectedIndex() == 0) {
    JOptionPane.showMessageDialog(this, "Please select a kursi from the combo box.", "Error", JOptionPane.ERROR_MESSAGE);
    buttonGroup1.clearSelection();
    } else if (rb_gold.isSelected()) {
    txt_harga.setText(String.valueOf(gold));
    }
    }//GEN-LAST:event_rb_goldActionPerformed

    private void txt_jumlahbeliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jumlahbeliKeyReleased
        // TODO add your handling code here:
        // hitung total bayar = jumlah beli * harga
        int harga, total_bayar, jumlah_beli;
        String str;
        
        
        
        str = txt_harga.getText();
        str = str.trim();
        //JOptionPane.showMessageDialog(this,str, 
        //                           "ERROR", JOptionPane.ERROR_MESSAGE);
        

        if((str.isEmpty()) || (str.isBlank())){
            JOptionPane.showMessageDialog(this,"Harga masih kosong", "ERROR", JOptionPane.INFORMATION_MESSAGE);
                                   txt_jumlahbeli.setText("");
        }else
        {
            harga = Integer.valueOf(txt_harga.getText());
            jumlah_beli = Integer.valueOf(txt_jumlahbeli.getText());
            total_bayar = harga * jumlah_beli;
            txt_totalbayar.setText(""+total_bayar);
        }
        
           
       
    }//GEN-LAST:event_txt_jumlahbeliKeyReleased

    private void txt_pembayaranKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pembayaranKeyReleased
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_txt_pembayaranKeyReleased

    private void btn_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inputActionPerformed
        // TODO add your handling code here:
        resetInput();
    }//GEN-LAST:event_btn_inputActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        int answer=JOptionPane.showConfirmDialog(null, "Anda akan keluar","Keluar",JOptionPane.OK_OPTION);
        if (answer == JOptionPane.OK_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        // TODO add your handling code here:
       String sti;
       
       sti = txt_kembalian.getText();
       sti = sti.trim();
        
        if((sti.isEmpty()) || (sti.isBlank())){
            JOptionPane.showMessageDialog(this,"Transaksi belum selesai", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        } else {
          txt_area.setText(
        "Nama Pembeli       :"+ txt_nama.getText()+"\n" +
        "Jumlah Pembelian   :"+ txt_jumlahbeli.getText()+"\n"+
        "total pembayaran   :"+ txt_totalbayar.getText()+"\n"+
        "Pembayaran         :"+ txt_pembayaran.getText()+"\n"+
        "Kembalian          :"+ txt_kembalian.getText()+"\n" +
        "Film               :" + txt_film.getText()
        );
        
        //open database
        Connection con;
        Statement stat;
        ResultSet rs;
        String sql;
        
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        //sql utk insert
        try {
            sql = "insert into riwayat(nama, Total, Pembayaran, Harga, Film) "
                    + "value ('" + txt_nama.getText() + "','" + txt_totalbayar.getText() + 
                    "','" + txt_pembayaran.getText() + "','" + txt_harga.getText() + "','" + txt_film.getText() + "')";
            stat.executeUpdate(sql);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }  
        }                          
        
        
        
        
        
        
    }//GEN-LAST:event_btn_printActionPerformed

    private void txt_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargaActionPerformed

    private void txt_filmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_filmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_filmActionPerformed

    private void rb_film1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_film1ActionPerformed
        // TODO add your handling code here:
        if(rb_film1.isSelected()){
            txt_film.setText("Her");
        }
    }//GEN-LAST:event_rb_film1ActionPerformed

    private void rb_film2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_film2ActionPerformed
        // TODO add your handling code here:
        if(rb_film2.isSelected()){
            txt_film.setText("Bladerunner");
        }
    }//GEN-LAST:event_rb_film2ActionPerformed

    private void rb_film3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_film3ActionPerformed
        // TODO add your handling code here:
        if(rb_film3.isSelected()){
            txt_film.setText("Drive");
        }
    }//GEN-LAST:event_rb_film3ActionPerformed

    private void txt_riwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_riwayatActionPerformed
        // TODO add your handling code here:
        Riwayat B = new Riwayat(txt_nama.getText());
        B.setVisible(true);
    }//GEN-LAST:event_txt_riwayatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TIKETANBIOSKOP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TIKETANBIOSKOP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TIKETANBIOSKOP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TIKETANBIOSKOP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Kursi;
    private javax.swing.JLabel Namafil;
    private javax.swing.JButton btn_input;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_print;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb_film1;
    private javax.swing.JRadioButton rb_film2;
    private javax.swing.JRadioButton rb_film3;
    private javax.swing.JRadioButton rb_gold;
    private javax.swing.JRadioButton rb_reguler;
    private javax.swing.JRadioButton rb_ultraxd;
    private javax.swing.JTextArea txt_area;
    private javax.swing.JTextField txt_film;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_jumlahbeli;
    private javax.swing.JTextField txt_kembalian;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_pembayaran;
    private javax.swing.JButton txt_riwayat;
    private javax.swing.JTextField txt_totalbayar;
    // End of variables declaration//GEN-END:variables
}
